A1. Implement the forward feature selection algorithm on your feature list. Find out the optimal set 
where maximum accuracy is achieved.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from skimage.io import imread, imshow

# Class A
imgAv1 = imread('2.jpg')
feature_matriximgAv1 = np.zeros((256,256)) 
feature_matriximgAv1.shape
for i in range(0,imgAv1.shape[0]):
    for j in range(0,imgAv1.shape[1]):
        feature_matriximgAv1[i][j] = ((int(imgAv1[i,j,0]) + int(imgAv1[i,j,1]) + int(imgAv1[i,j,2]))/3)
featureAv1 = np.reshape(feature_matriximgAv1, (256*256))

imgAv2 = imread('3.jpg')
feature_matriximgAv2 = np.zeros((256,256)) 
feature_matriximgAv2.shape
for i in range(0,imgAv2.shape[0]):
    for j in range(0,imgAv2.shape[1]):
        feature_matriximgAv2[i][j] = ((int(imgAv2[i,j,0]) + int(imgAv2[i,j,1]) + int(imgAv2[i,j,2]))/3)
featureAv2 = np.reshape(feature_matriximgAv2, (256*256))

imgAv3 = imread('4.jpg')
feature_matriximgAv3 = np.zeros((256,256)) 
feature_matriximgAv3.shape
for i in range(0,imgAv3.shape[0]):
    for j in range(0,imgAv3.shape[1]):
        feature_matriximgAv3[i][j] = ((int(imgAv3[i,j,0]) + int(imgAv3[i,j,1]) + int(imgAv3[i,j,2]))/3)
featureAv3 = np.reshape(feature_matriximgAv3, (256*256))

imgAv4 = imread('5.jpg')
feature_matriximgAv4 = np.zeros((256,256)) 
feature_matriximgAv4.shape
for i in range(0,imgAv4.shape[0]):
    for j in range(0,imgAv4.shape[1]):
        feature_matriximgAv4[i][j] = ((int(imgAv4[i,j,0]) + int(imgAv4[i,j,1]) + int(imgAv4[i,j,2]))/3)
featureAv4 = np.reshape(feature_matriximgAv4, (256*256))

imgAv5 = imread('6.jpg')
feature_matriximgAv5 = np.zeros((256,256)) 
feature_matriximgAv5.shape
for i in range(0,imgAv5.shape[0]):
    for j in range(0,imgAv5.shape[1]):
        feature_matriximgAv5[i][j] = ((int(imgAv5[i,j,0]) + int(imgAv5[i,j,1]) + int(imgAv5[i,j,2]))/3)
featureAv5 = np.reshape(feature_matriximgAv5, (256*256))

ClassA=np.array([featureAv1,featureAv2,featureAv3,featureAv4,featureAv5])

print(ClassA)

# Class B
imgBv1 = imread('7.jpg')
feature_matriximgBv1 = np.zeros((256,256)) 
feature_matriximgBv1.shape
for i in range(0,imgBv1.shape[0]):
    for j in range(0,imgBv1.shape[1]):
        feature_matriximgBv1[i][j] = ((int(imgBv1[i,j,0]) + int(imgBv1[i,j,1]) + int(imgBv1[i,j,2]))/3)
featureBv1 = np.reshape(feature_matriximgBv1, (256*256))

imgBv2 = imread('8.jpg')
feature_matriximgBv2 = np.zeros((256,256)) 
feature_matriximgBv2.shape
for i in range(0,imgBv2.shape[0]):
    for j in range(0,imgBv2.shape[1]):
        feature_matriximgBv2[i][j] = ((int(imgBv2[i,j,0]) + int(imgBv2[i,j,1]) + int(imgBv2[i,j,2]))/3)
featureBv2 = np.reshape(feature_matriximgBv2, (256*256))

imgBv3 = imread('9.jpg')
feature_matriximgBv3 = np.zeros((256,256)) 
feature_matriximgBv3.shape
for i in range(0,imgBv3.shape[0]):
    for j in range(0,imgBv3.shape[1]):
        feature_matriximgBv3[i][j] = ((int(imgBv3[i,j,0]) + int(imgBv3[i,j,1]) + int(imgBv3[i,j,2]))/3)
featureBv3 = np.reshape(feature_matriximgBv3, (256*256))

imgBv4 = imread('10.jpg')
feature_matriximgBv4 = np.zeros((256,256)) 
feature_matriximgBv4.shape
for i in range(0,imgBv4.shape[0]):
    for j in range(0,imgBv4.shape[1]):
        feature_matriximgBv4[i][j] = ((int(imgBv4[i,j,0]) + int(imgBv4[i,j,1]) + int(imgBv4[i,j,2]))/3)
featureBv4 = np.reshape(feature_matriximgBv4, (256*256))

imgBv5 = imread('11.jpg')
feature_matriximgBv5 = np.zeros((256,256)) 
feature_matriximgBv5.shape
for i in range(0,imgBv5.shape[0]):
    for j in range(0,imgBv5.shape[1]):
        feature_matriximgBv5[i][j] = ((int(imgBv5[i,j,0]) + int(imgBv5[i,j,1]) + int(imgBv5[i,j,2]))/3)
featureBv5 = np.reshape(feature_matriximgBv5, (256*256))

ClassB=np.array([featureBv1,featureBv2,featureBv3,featureBv4,featureBv5])

print(ClassB)

[[240.         242.         244.         ... 184.66666667 180.
  184.        ]
 [ 61.          60.66666667  61.66666667 ...  72.66666667  70.66666667
   68.66666667]
 [202.33333333 202.33333333 202.33333333 ... 113.33333333  70.33333333
   80.33333333]
 [238.66666667 240.66666667 242.66666667 ... 225.33333333 224.66666667
  184.66666667]
 [233.         232.         231.         ...  23.          15.
    8.        ]]
[[164.33333333 163.33333333 162.33333333 ... 210.66666667 212.66666667
  214.66666667]
 [130.         130.         130.         ...  96.33333333 122.66666667
  103.66666667]
 [242.         245.         246.         ... 192.66666667 196.33333333
  199.33333333]
 [121.66666667 119.66666667 117.66666667 ... 113.66666667 113.66666667
   74.66666667]
 [208.33333333 211.33333333 211.33333333 ... 102.          86.
   90.33333333]]


In [ ]:
meanAv1=featureAv1.mean(axis=0)
meanAv2=featureAv2.mean(axis=0)
meanAv3=featureAv3.mean(axis=0)
meanAv4=featureAv4.mean(axis=0)
meanAv5=featureAv5.mean(axis=0)

ClassA_label=np.array([meanAv1,meanAv2,meanAv3,meanAv4,meanAv5])
print(ClassA_label)

meanBv1=featureBv1.mean(axis=0)
meanBv2=featureBv2.mean(axis=0)
meanBv3=featureBv3.mean(axis=0)
meanBv4=featureBv4.mean(axis=0)
meanBv5=featureBv5.mean(axis=0)

ClassB_label=np.array([meanBv1,meanBv2,meanBv3,meanBv4,meanBv5])
print(ClassB_label)

# for i in range(0,5):
#   if ClassA_label[i]<100:
#     ClassA_label[i]=0
#   else:
#     ClassA_label[i]=1

for i in range(0,5):
  if ClassA_label[i]<95:
    ClassA_label[i]=-1
  elif ClassA_label[i]<110:
    ClassA_label[i]=0
  else:
    ClassA_label[i]=1

for i in range(0,5):
  if ClassB_label[i]<95:
    ClassB_label[i]=-1
  elif ClassB_label[i]<110:
    ClassB_label[i]=0
  else:
    ClassB_label[i]=1

print(ClassA_label)
print(ClassB_label)

[146.08732605  84.6669515  109.73945618 122.08019511 127.38117981]
[127.17301432  92.02892049 119.04534403  90.80475871 106.46661886]
[ 1. -1.  0.  1.  1.]
[ 1. -1.  1. -1.  0.]


In [ ]:
Class=np.concatenate((ClassA,ClassB),axis=0)
print(Class)

Class_label=np.concatenate((ClassA_label,ClassB_label),axis=0)
print(Class_label)

[[240.         242.         244.         ... 184.66666667 180.
  184.        ]
 [ 61.          60.66666667  61.66666667 ...  72.66666667  70.66666667
   68.66666667]
 [202.33333333 202.33333333 202.33333333 ... 113.33333333  70.33333333
   80.33333333]
 ...
 [242.         245.         246.         ... 192.66666667 196.33333333
  199.33333333]
 [121.66666667 119.66666667 117.66666667 ... 113.66666667 113.66666667
   74.66666667]
 [208.33333333 211.33333333 211.33333333 ... 102.          86.
   90.33333333]]
[ 1. -1.  0.  1.  1.  1. -1.  1. -1.  0.]


In [ ]:

from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.linear_model import LinearRegression

sfs = SFS(LinearRegression(), k_features=11, forward=True, floating=False, scoring = 'r2', cv = 0)

In [ ]:
sfs.fit(ClassA, ClassA_label)
sfs.k_feature_names_ 

('0', '1', '2', '3', '4', '5', '6', '7', '3164', '19159', '33454')

A2. Implement the backward feature removal algorithm. Identify the optimal set with accuracy 
maximization as the target. Compare the results obtained with the results from A1.


In [ ]:

sbs = SFS(LinearRegression(), k_features=5, forward=False, floating=False, cv=0)
sbs.fit(ClassA, ClassA_label)

A3. Check the variance associated with each attribute for your data set. If your data has categorical 
features, you may derive the variance after label coding.

In [ ]:

import statistics
 
v1=statistics.variance(featureAv1)
v2=statistics.variance(featureAv2)
v3=statistics.variance(featureAv3)
v4=statistics.variance(featureAv4)
v5=statistics.variance(featureAv5)

print(v1, v2, v3, v4, v5)

5769.362330725995 4180.231031683067 4906.3701396674605 6860.158930666645 7622.938580274483


A4. Perform PCA on your data set. Observe the variances along the principal components. Identify 
the features needed to capture 95% of data variance. Let’s say the number of features needed is K.

In [ ]:
import numpy as np
from sklearn.decomposition import PCA

pca = PCA(n_components=2, svd_solver='full')
pca.fit(ClassA)

print(pca.explained_variance_ratio_)

print(pca.singular_values_)


[0.53106975 0.26724811]
[22634.53545375 16056.58294254]


A5. Transform your data with the initial K PC’s. Calculate the accuracy using the transformed 
dataset

In [ ]:
pca = PCA(n_components=None)
X_train_pca = pca.fit_transform(ClassA)
pca.explained_variance_ratio_

array([5.31069752e-01, 2.67248114e-01, 1.24751980e-01, 7.69301548e-02,
       1.27042082e-30])